# Generated by Django 4.2.5 on 2023-09-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='thumbnail',
            field=models.ImageField(blank=True, default='../../frontend/images/placeholder.png', null=True, upload_to='images'),
        ),
    ]
