# Generated by Django 4.2.5 on 2023-10-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_post_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.profile'),
        ),
    ]
