# Generated by Django 3.2.23 on 2023-11-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_notify_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify_user',
            name='user',
        ),
    ]
